version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

  quote_api:
    build: .
    container_name: quote_api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
